openapi: 3.0.3
info:
  title: sample-api
  version: 1.0.0
  description: Sample API
paths:
  /test:
    post:
      tags:
        - sample-controller
      requestBody:
        description: A JSON object containing the request
        required: true
        content:
          application/json:
            schema:
              $ref: 'sample-types.json#/$defs/Request'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: 'sample-types.json#/$defs/Response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: 'sample-types.json#/$defs/Response'
          description: Invalid
        '500':
          content:
            application/json:
              schema:
                $ref: 'sample-types.json#/$defs/Response'
          description: Error
      operationId: getSample
      summary: Operation to retrieve a sample

